version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/db
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m weather.telegram_bot.bot
    volumes:
      - .:/app
      - db_data:/app/db
    depends_on:
      - web

volumes:
  db_data:
